Lec3 dz2 modal
js-tasks-ru/htmlcss-20220317_starkhv pull request #10
Opened 2022-04-08 09:43 UTC by starkhv70

2022-04-08 09:43 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-04-08 09:50 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-04-08 12:48 UTC, GSemikozov requested changes

2022-04-08 12:48 UTC, GSemikozov commented on 05-lection3/02-modal/modal.css
> +    opacity: .5;
фон через rgba, иначе вся модалка будет полупрозрачной

2022-04-11 15:22 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-04-12 11:29 UTC, GSemikozov approved these changes

2022-04-12 11:29 UTC, merged